export type GFTSFeedFileName =
  | 'agency'
  | 'stops'
  | 'routes'
  | 'trips'
  | 'stop_times'
  | 'calendar'
  | 'calendar_dates'
  | 'fare_attributes'
  | 'fare_rule'
  | 'shape'
  | 'frequencie'
  | 'transfer'
  | 'pathway'
  | 'level'
  | 'feed_inf'
  | 'translation'
  | 'attribution';
