name: Release Mobile App

on:
  workflow_dispatch:
    inputs:
      run-build:
        description: Whether to build with EAS Build or not
        type: boolean
        required: true
        default: true

      platform:
        description: Platform to build for
        type: choice
        required: false
        default: all
        options:
          - all
          - android
          - ios

      profile:
        description: EAS build profile
        type: choice
        required: false
        default: development
        options:
          - development
          - preview
          - preview:store
          - production

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Release
        working-directory: apps/mobile-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm dlx semantic-release@19.0.5

  eas-build:
    name: EAS Build
    runs-on: ubuntu-latest
    needs: release
    if: ${{ github.event.inputs.run-build == true }}
    outputs:
      artifactUrl: ${{ steps.get-artifact-url.outputs.artifactUrl }}
    steps:
      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build mobile app
        working-directory: apps/mobile-app
        run: eas build --non-interactive --wait --platform=${{ github.event.inputs.platform }} --profile=${{ github.event.inputs.profile }}

      - name: Get artifact URL
        id: get-artifact-url
        working-directory: apps/mobile-app
        run: echo "artifactUrl=$(eas build:list --platform ${{ github.event.inputs.platform }} --buildProfile ${{ github.event.inputs.profile }} --limit 1 --non-interactive | jq -r '.[0].artifacts.applicationArchiveUrl')"
